/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shuaib UWC
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CategoryPanel = new javax.swing.JPanel();
        Mathematics_btn = new javax.swing.JButton();
        ComSci_btn = new javax.swing.JButton();
        Physics_btn = new javax.swing.JButton();
        Accounting_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        MathematicsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MathematicsTable = new javax.swing.JTable();
        Math_Closebtn = new javax.swing.JButton();
        ComSciPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ComSciTable = new javax.swing.JTable();
        ComSci_Closebtn = new javax.swing.JButton();
        PhysicsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        PhysicsTable = new javax.swing.JTable();
        Physics_Closebtn = new javax.swing.JButton();
        AccountingPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        AccountingTable = new javax.swing.JTable();
        Accounting_Closebtn = new javax.swing.JButton();
        InsertBookPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BookName_Insert = new javax.swing.JTextField();
        BookID_Insert = new javax.swing.JTextField();
        BookCategory_Insert = new javax.swing.JTextField();
        InsertBook_btn = new javax.swing.JButton();
        InsertBook_Closebtn = new javax.swing.JButton();
        EditBookPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        OldBookName = new javax.swing.JTextField();
        NewBookName = new javax.swing.JTextField();
        OldBookID = new javax.swing.JTextField();
        NewBookID = new javax.swing.JTextField();
        OldBookCategory = new javax.swing.JTextField();
        NewBookCategory = new javax.swing.JTextField();
        EditBook_btn = new javax.swing.JButton();
        EditBook_Closebtn = new javax.swing.JButton();
        DeleteBookPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        BookName_Delete = new javax.swing.JTextField();
        BookID_Delete = new javax.swing.JTextField();
        BookCategory_Delete = new javax.swing.JTextField();
        DeleteBook_btn = new javax.swing.JButton();
        DeleteBook_Closebtn = new javax.swing.JButton();
        ReportsPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        BooksOnLoan_Table = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        BooksOverdue_Table = new javax.swing.JTable();
        Repots_Closebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ViewBooks = new javax.swing.JButton();
        InsertBookbtn = new javax.swing.JButton();
        EditBookbtn = new javax.swing.JButton();
        DeleteBookbtn = new javax.swing.JButton();
        Reportsbtn = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CategoryPanel.setBackground(new java.awt.Color(34, 0, 0));
        CategoryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CategoryPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CategoryPanelMouseExited(evt);
            }
        });
        CategoryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mathematics_btn.setForeground(new java.awt.Color(204, 204, 204));
        Mathematics_btn.setText("Mathematics");
        Mathematics_btn.setBorder(null);
        Mathematics_btn.setContentAreaFilled(false);
        Mathematics_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mathematics_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mathematics_btnMouseEntered(evt);
            }
        });
        Mathematics_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mathematics_btnActionPerformed(evt);
            }
        });
        CategoryPanel.add(Mathematics_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 100, 20));

        ComSci_btn.setForeground(new java.awt.Color(204, 204, 204));
        ComSci_btn.setText("Computer Science");
        ComSci_btn.setBorder(null);
        ComSci_btn.setContentAreaFilled(false);
        ComSci_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComSci_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ComSci_btnMouseEntered(evt);
            }
        });
        ComSci_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComSci_btnActionPerformed(evt);
            }
        });
        CategoryPanel.add(ComSci_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 20));

        Physics_btn.setForeground(new java.awt.Color(204, 204, 204));
        Physics_btn.setText("Physics");
        Physics_btn.setBorder(null);
        Physics_btn.setContentAreaFilled(false);
        Physics_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Physics_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Physics_btnMouseEntered(evt);
            }
        });
        Physics_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Physics_btnActionPerformed(evt);
            }
        });
        CategoryPanel.add(Physics_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, 20));

        Accounting_btn.setForeground(new java.awt.Color(204, 204, 204));
        Accounting_btn.setText("Accounting");
        Accounting_btn.setBorder(null);
        Accounting_btn.setContentAreaFilled(false);
        Accounting_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Accounting_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Accounting_btnMouseEntered(evt);
            }
        });
        Accounting_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accounting_btnActionPerformed(evt);
            }
        });
        CategoryPanel.add(Accounting_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 100, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        CategoryPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel1.add(CategoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 0, 170));

        MathematicsPanel.setBackground(new java.awt.Color(51, 0, 0));
        MathematicsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mathematics");
        MathematicsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 110, 30));

        MathematicsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Book ID"
            }
        ));
        jScrollPane1.setViewportView(MathematicsTable);

        MathematicsPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 440, 160));

        Math_Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_20px.png"))); // NOI18N
        Math_Closebtn.setContentAreaFilled(false);
        Math_Closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Math_Closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Math_ClosebtnActionPerformed(evt);
            }
        });
        MathematicsPanel.add(Math_Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 0, 30, 20));

        jPanel1.add(MathematicsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 0, 240));

        ComSciPanel.setBackground(new java.awt.Color(51, 0, 0));
        ComSciPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Computer Science");
        ComSciPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 140, 30));

        ComSciTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Book ID"
            }
        ));
        jScrollPane2.setViewportView(ComSciTable);

        ComSciPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 440, 160));

        ComSci_Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_20px.png"))); // NOI18N
        ComSci_Closebtn.setContentAreaFilled(false);
        ComSci_Closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComSci_Closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComSci_ClosebtnActionPerformed(evt);
            }
        });
        ComSciPanel.add(ComSci_Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 0, 30, 20));

        jPanel1.add(ComSciPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 0, 240));

        PhysicsPanel.setBackground(new java.awt.Color(51, 0, 0));
        PhysicsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Physics");
        PhysicsPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 60, 20));

        PhysicsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Book ID"
            }
        ));
        jScrollPane3.setViewportView(PhysicsTable);

        PhysicsPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 440, 160));

        Physics_Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_20px.png"))); // NOI18N
        Physics_Closebtn.setContentAreaFilled(false);
        Physics_Closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Physics_Closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Physics_ClosebtnActionPerformed(evt);
            }
        });
        PhysicsPanel.add(Physics_Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 0, 30, 20));

        jPanel1.add(PhysicsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 0, 240));

        AccountingPanel.setBackground(new java.awt.Color(51, 0, 0));
        AccountingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Accounting");
        AccountingPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 110, 40));

        AccountingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Book ID"
            }
        ));
        jScrollPane4.setViewportView(AccountingTable);

        AccountingPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 440, 160));

        Accounting_Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_20px.png"))); // NOI18N
        Accounting_Closebtn.setContentAreaFilled(false);
        Accounting_Closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Accounting_Closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accounting_ClosebtnActionPerformed(evt);
            }
        });
        AccountingPanel.add(Accounting_Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 0, 30, 20));

        jPanel1.add(AccountingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 0, 240));

        InsertBookPanel.setBackground(new java.awt.Color(51, 0, 0));
        InsertBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INSERT BOOK");
        InsertBookPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Book Name");
        InsertBookPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Book ID");
        InsertBookPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Book Category");
        InsertBookPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));
        InsertBookPanel.add(BookName_Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 230, -1));
        InsertBookPanel.add(BookID_Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 230, -1));
        InsertBookPanel.add(BookCategory_Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 230, -1));

        InsertBook_btn.setBackground(new java.awt.Color(34, 0, 0));
        InsertBook_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        InsertBook_btn.setForeground(new java.awt.Color(255, 255, 255));
        InsertBook_btn.setText("INSERT BOOK");
        InsertBook_btn.setBorder(null);
        InsertBook_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InsertBookPanel.add(InsertBook_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, 30));

        InsertBook_Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_20px.png"))); // NOI18N
        InsertBook_Closebtn.setContentAreaFilled(false);
        InsertBook_Closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InsertBook_Closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBook_ClosebtnActionPerformed(evt);
            }
        });
        InsertBookPanel.add(InsertBook_Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 20, 20));

        jPanel1.add(InsertBookPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 0, 230));

        EditBookPanel.setBackground(new java.awt.Color(51, 0, 0));
        EditBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("EDIT BOOK");
        EditBookPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 11, 90, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Old Book Name");
        EditBookPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 45, -1, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("New Book Name");
        EditBookPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Old Book ID");
        EditBookPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("New Book ID");
        EditBookPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Old Book Category");
        EditBookPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("New Book Category");
        EditBookPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 20));

        OldBookName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EditBookPanel.add(OldBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 220, 25));

        NewBookName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EditBookPanel.add(NewBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 220, 25));

        OldBookID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EditBookPanel.add(OldBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 220, 25));

        NewBookID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EditBookPanel.add(NewBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 220, 25));

        OldBookCategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EditBookPanel.add(OldBookCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 220, 25));

        NewBookCategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EditBookPanel.add(NewBookCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 220, 25));

        EditBook_btn.setBackground(new java.awt.Color(34, 0, 0));
        EditBook_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EditBook_btn.setForeground(new java.awt.Color(255, 255, 255));
        EditBook_btn.setText("EDIT BOOK");
        EditBook_btn.setBorder(null);
        EditBook_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditBookPanel.add(EditBook_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 110, 30));

        EditBook_Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_20px.png"))); // NOI18N
        EditBook_Closebtn.setContentAreaFilled(false);
        EditBook_Closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditBook_Closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBook_ClosebtnActionPerformed(evt);
            }
        });
        EditBookPanel.add(EditBook_Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 30, 20));

        jPanel1.add(EditBookPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 0, 310));

        DeleteBookPanel.setBackground(new java.awt.Color(51, 0, 0));
        DeleteBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("DELETE BOOK");
        DeleteBookPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 110, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Book Name");
        DeleteBookPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Book ID");
        DeleteBookPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Book Category");
        DeleteBookPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));
        DeleteBookPanel.add(BookName_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 230, -1));
        DeleteBookPanel.add(BookID_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 230, -1));
        DeleteBookPanel.add(BookCategory_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 230, -1));

        DeleteBook_btn.setBackground(new java.awt.Color(34, 0, 0));
        DeleteBook_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteBook_btn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBook_btn.setText("DELETE BOOK");
        DeleteBook_btn.setBorder(null);
        DeleteBook_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteBookPanel.add(DeleteBook_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, 30));

        DeleteBook_Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_20px.png"))); // NOI18N
        DeleteBook_Closebtn.setContentAreaFilled(false);
        DeleteBook_Closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteBook_Closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBook_ClosebtnActionPerformed(evt);
            }
        });
        DeleteBookPanel.add(DeleteBook_Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 20, 20));

        jPanel1.add(DeleteBookPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 0, 230));

        ReportsPanel.setBackground(new java.awt.Color(51, 0, 0));
        ReportsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("REPORTS");
        ReportsPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 76, 26));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("Books On Loan");
        ReportsPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, 30));

        BooksOnLoan_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Book Name", "Book ID", "Lend Date", "Return Date"
            }
        ));
        jScrollPane5.setViewportView(BooksOnLoan_Table);

        ReportsPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 110));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 153, 153));
        jLabel25.setText("Books Overdue");
        ReportsPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        BooksOverdue_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Book Name", "Book ID", "Lend Date", "Title 5"
            }
        ));
        jScrollPane6.setViewportView(BooksOverdue_Table);

        ReportsPanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 110));

        Repots_Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_20px.png"))); // NOI18N
        Repots_Closebtn.setBorder(null);
        Repots_Closebtn.setContentAreaFilled(false);
        Repots_Closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Repots_Closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Repots_ClosebtnActionPerformed(evt);
            }
        });
        ReportsPanel.add(Repots_Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 20, 20));

        jPanel1.add(ReportsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 0, 360));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 780, -1));

        ViewBooks.setBackground(new java.awt.Color(34, 0, 0));
        ViewBooks.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ViewBooks.setForeground(new java.awt.Color(255, 255, 255));
        ViewBooks.setText("View Books");
        ViewBooks.setBorder(null);
        ViewBooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewBooksMouseExited(evt);
            }
        });
        ViewBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBooksActionPerformed(evt);
            }
        });
        jPanel1.add(ViewBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 40));

        InsertBookbtn.setBackground(new java.awt.Color(34, 0, 0));
        InsertBookbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        InsertBookbtn.setForeground(new java.awt.Color(255, 255, 255));
        InsertBookbtn.setText("Insert Book");
        InsertBookbtn.setBorder(null);
        InsertBookbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InsertBookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBookbtnActionPerformed(evt);
            }
        });
        jPanel1.add(InsertBookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 170, 40));

        EditBookbtn.setBackground(new java.awt.Color(34, 0, 0));
        EditBookbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EditBookbtn.setForeground(new java.awt.Color(255, 255, 255));
        EditBookbtn.setText("Edit Book");
        EditBookbtn.setBorder(null);
        EditBookbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditBookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBookbtnActionPerformed(evt);
            }
        });
        jPanel1.add(EditBookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 170, 40));

        DeleteBookbtn.setBackground(new java.awt.Color(34, 0, 0));
        DeleteBookbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteBookbtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBookbtn.setText("Delete Book");
        DeleteBookbtn.setBorder(null);
        DeleteBookbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteBookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBookbtnActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteBookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 40));

        Reportsbtn.setBackground(new java.awt.Color(34, 0, 0));
        Reportsbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Reportsbtn.setForeground(new java.awt.Color(255, 255, 255));
        Reportsbtn.setText("Reports");
        Reportsbtn.setBorder(null);
        Reportsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reportsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Reportsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 170, 40));

        LogOut.setBackground(new java.awt.Color(34, 0, 0));
        LogOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 0, 0));
        LogOut.setText("Log Out");
        LogOut.setBorder(null);
        LogOut.setBorderPainted(false);
        LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpeg"))); // NOI18N
        jLabel1.setText(" ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        setVisible(false);
        new LoginPage().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_LogOutActionPerformed

    private void ViewBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBooksActionPerformed
          // TODO add your handling code here:
         
    }//GEN-LAST:event_ViewBooksActionPerformed

    private void ViewBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewBooksMouseEntered
        CategoryPanel.setSize(100, 170);// TODO add your handling code here:
    }//GEN-LAST:event_ViewBooksMouseEntered

    private void ViewBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewBooksMouseExited
        CategoryPanel.setSize(0,0);// TODO add your handling code here:
    }//GEN-LAST:event_ViewBooksMouseExited

    private void Mathematics_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mathematics_btnMouseEntered
        CategoryPanel.setSize(100,170);// TODO add your handling code here:
    }//GEN-LAST:event_Mathematics_btnMouseEntered

    private void Mathematics_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mathematics_btnActionPerformed
        MathematicsPanel.setSize(480,240);// TODO add your handling code here:

        ComSciPanel.setSize(0,0);
        PhysicsPanel.setSize(0,0);
        AccountingPanel.setSize(0,0);
        InsertBookPanel.setSize(0,0);
        ReportsPanel.setSize(0,0);
        DeleteBookPanel.setSize(0,0);
        EditBookPanel.setSize(0,0);
    }//GEN-LAST:event_Mathematics_btnActionPerformed

    private void ComSci_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComSci_btnMouseEntered
        CategoryPanel.setSize(100,170);// TODO add your handling code here:
    }//GEN-LAST:event_ComSci_btnMouseEntered

    private void ComSci_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComSci_btnActionPerformed
        ComSciPanel.setSize(480,240);// TODO add your handling code here:

        MathematicsPanel.setSize(0,0);
        PhysicsPanel.setSize(0,0);
        AccountingPanel.setSize(0,0);
        InsertBookPanel.setSize(0,0);
        ReportsPanel.setSize(0,0);
        DeleteBookPanel.setSize(0,0);
        EditBookPanel.setSize(0,0);
    }//GEN-LAST:event_ComSci_btnActionPerformed

    private void Physics_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Physics_btnMouseEntered
        CategoryPanel.setSize(100,170);// TODO add your handling code here:
    }//GEN-LAST:event_Physics_btnMouseEntered

    private void Physics_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Physics_btnActionPerformed
        PhysicsPanel.setSize(480,240);// TODO add your handling code here:

        ComSciPanel.setSize(0,0);
        MathematicsPanel.setSize(0,0);
        AccountingPanel.setSize(0,0);
        InsertBookPanel.setSize(0,0);
        ReportsPanel.setSize(0,0);
        DeleteBookPanel.setSize(0,0);
        EditBookPanel.setSize(0,0);
    }//GEN-LAST:event_Physics_btnActionPerformed

    private void Accounting_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Accounting_btnMouseEntered
        CategoryPanel.setSize(100,170);// TODO add your handling code here:
    }//GEN-LAST:event_Accounting_btnMouseEntered

    private void Accounting_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accounting_btnActionPerformed
        AccountingPanel.setSize(480,240);// TODO add your handling code here:

        ComSciPanel.setSize(0,0);
        MathematicsPanel.setSize(0,0);
        PhysicsPanel.setSize(0,0);
        InsertBookPanel.setSize(0,0);
        ReportsPanel.setSize(0,0);
        DeleteBookPanel.setSize(0,0);
        EditBookPanel.setSize(0,0);
    }//GEN-LAST:event_Accounting_btnActionPerformed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        CategoryPanel.setSize(100,170);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void CategoryPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryPanelMouseEntered
        CategoryPanel.setSize(100,170);// TODO add your handling code here:
    }//GEN-LAST:event_CategoryPanelMouseEntered

    private void CategoryPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryPanelMouseExited
        CategoryPanel.setSize(0,0);// TODO add your handling code here:
    }//GEN-LAST:event_CategoryPanelMouseExited

    private void Math_ClosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Math_ClosebtnActionPerformed
        MathematicsPanel.setSize(0,0);// TODO add your handling code here:
    }//GEN-LAST:event_Math_ClosebtnActionPerformed

    private void ComSci_ClosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComSci_ClosebtnActionPerformed
        ComSciPanel.setSize(0,0);// TODO add your handling code here:
    }//GEN-LAST:event_ComSci_ClosebtnActionPerformed

    private void Physics_ClosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Physics_ClosebtnActionPerformed
        PhysicsPanel.setSize(0,0);// TODO add your handling code here:
    }//GEN-LAST:event_Physics_ClosebtnActionPerformed

    private void Accounting_ClosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accounting_ClosebtnActionPerformed
        AccountingPanel.setSize(0,0);// TODO add your handling code here:
    }//GEN-LAST:event_Accounting_ClosebtnActionPerformed

    private void InsertBookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBookbtnActionPerformed
        InsertBookPanel.setSize(420,230);// TODO add your handling code here:
        
        ComSciPanel.setSize(0,0);
        MathematicsPanel.setSize(0,0);
        PhysicsPanel.setSize(0,0);
        AccountingPanel.setSize(0,0);
        ReportsPanel.setSize(0,0);
        DeleteBookPanel.setSize(0,0);
        EditBookPanel.setSize(0,0);
    }//GEN-LAST:event_InsertBookbtnActionPerformed

    private void InsertBook_ClosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBook_ClosebtnActionPerformed
        InsertBookPanel.setSize(0,0);// TODO add your handling code here:
    }//GEN-LAST:event_InsertBook_ClosebtnActionPerformed

    private void EditBookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBookbtnActionPerformed
        EditBookPanel.setSize(440,310);// TODO add your handling code here:
        
        ComSciPanel.setSize(0,0);
        MathematicsPanel.setSize(0,0);
        PhysicsPanel.setSize(0,0);
        AccountingPanel.setSize(0,0);
        InsertBookPanel.setSize(0,0);
        ReportsPanel.setSize(0,0);
        DeleteBookPanel.setSize(0,0);
    }//GEN-LAST:event_EditBookbtnActionPerformed

    private void EditBook_ClosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBook_ClosebtnActionPerformed
        EditBookPanel.setSize(0,0);// TODO add your handling code here:
    }//GEN-LAST:event_EditBook_ClosebtnActionPerformed

    private void DeleteBookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookbtnActionPerformed
        DeleteBookPanel.setSize(420,230);// TODO add your handling code here:
        
        ComSciPanel.setSize(0,0);
        MathematicsPanel.setSize(0,0);
        PhysicsPanel.setSize(0,0);
        AccountingPanel.setSize(0,0);
        InsertBookPanel.setSize(0,0);
        EditBookPanel.setSize(0,0);
        ReportsPanel.setSize(0,0);
    }//GEN-LAST:event_DeleteBookbtnActionPerformed

    private void DeleteBook_ClosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBook_ClosebtnActionPerformed
        DeleteBookPanel.setSize(0,0); // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBook_ClosebtnActionPerformed

    private void ReportsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsbtnActionPerformed
        ReportsPanel.setSize(500,360);// TODO add your handling code here:
        
        ComSciPanel.setSize(0,0);
        MathematicsPanel.setSize(0,0);
        PhysicsPanel.setSize(0,0);
        AccountingPanel.setSize(0,0);
        InsertBookPanel.setSize(0,0);
        EditBookPanel.setSize(0,0);
        DeleteBookPanel.setSize(0,0);
    }//GEN-LAST:event_ReportsbtnActionPerformed

    private void Repots_ClosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Repots_ClosebtnActionPerformed
       ReportsPanel.setSize(0,0); // TODO add your handling code here:
    }//GEN-LAST:event_Repots_ClosebtnActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountingPanel;
    private javax.swing.JTable AccountingTable;
    private javax.swing.JButton Accounting_Closebtn;
    private javax.swing.JButton Accounting_btn;
    private javax.swing.JTextField BookCategory_Delete;
    private javax.swing.JTextField BookCategory_Insert;
    private javax.swing.JTextField BookID_Delete;
    private javax.swing.JTextField BookID_Insert;
    private javax.swing.JTextField BookName_Delete;
    private javax.swing.JTextField BookName_Insert;
    private javax.swing.JTable BooksOnLoan_Table;
    private javax.swing.JTable BooksOverdue_Table;
    private javax.swing.JPanel CategoryPanel;
    private javax.swing.JPanel ComSciPanel;
    private javax.swing.JTable ComSciTable;
    private javax.swing.JButton ComSci_Closebtn;
    private javax.swing.JButton ComSci_btn;
    private javax.swing.JPanel DeleteBookPanel;
    private javax.swing.JButton DeleteBook_Closebtn;
    private javax.swing.JButton DeleteBook_btn;
    private javax.swing.JButton DeleteBookbtn;
    private javax.swing.JPanel EditBookPanel;
    private javax.swing.JButton EditBook_Closebtn;
    private javax.swing.JButton EditBook_btn;
    private javax.swing.JButton EditBookbtn;
    private javax.swing.JPanel InsertBookPanel;
    private javax.swing.JButton InsertBook_Closebtn;
    private javax.swing.JButton InsertBook_btn;
    private javax.swing.JButton InsertBookbtn;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton Math_Closebtn;
    private javax.swing.JPanel MathematicsPanel;
    private javax.swing.JTable MathematicsTable;
    private javax.swing.JButton Mathematics_btn;
    private javax.swing.JTextField NewBookCategory;
    private javax.swing.JTextField NewBookID;
    private javax.swing.JTextField NewBookName;
    private javax.swing.JTextField OldBookCategory;
    private javax.swing.JTextField OldBookID;
    private javax.swing.JTextField OldBookName;
    private javax.swing.JPanel PhysicsPanel;
    private javax.swing.JTable PhysicsTable;
    private javax.swing.JButton Physics_Closebtn;
    private javax.swing.JButton Physics_btn;
    private javax.swing.JPanel ReportsPanel;
    private javax.swing.JButton Reportsbtn;
    private javax.swing.JButton Repots_Closebtn;
    private javax.swing.JButton ViewBooks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
